version: 0.2

phases:
  install:
    commands:
    # Install Angular CLI, If you are not using Angular 6, install angular/cli@1.7.0 or lower, confirm by running ng -v inside your project folder
    - npm i @angular/cli@6.0.8
    # Install node dependancies.
    - npm i
    - npm run lint
    - ng build
